import logging

# --- LOGGING CONFIGURATION ---
LOG_LEVEL = logging.INFO
LOG_FORMAT = '%(asctime)s - %(levelname)s - [%(name)s] - %(message)s'

# --- SEARCH AGENT CONFIGURATION ---
DUCKDUCKGO_DELAY = 1.0
WIKIPEDIA_DELAY = 0.8
SERPAPI_DELAY = 1.0
MULTI_SEARCH_CONCURRENCY = 3

# --- SCRAPER CONFIGURATION ---
SCRAPER_MAX_RETRIES = 2
SCRAPER_TIMEOUT = 20
SCRAPER_RATE_LIMIT_DELAY = 1.0
SCRAPER_MAX_CONCURRENT = 5

# --- RAG AGENT CONFIGURATION ---
RAG_CHUNK_SIZE = 400
RAG_CHUNK_OVERLAP = 50
RAG_USE_EMBEDDINGS = True